# Generated by Django 2.2 on 2019-04-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20190402_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.tipo_usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
