# Generated by Django 2.2 on 2019-04-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20190402_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, max_length=5),
        ),
    ]
